# Generated by Django 4.1.1 on 2022-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=255, verbose_name='Telefone')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('cpf', models.CharField(max_length=11, verbose_name='Cpf')),
            ],
        ),
    ]
